### ISSUE TITLE
CMake build Error，Can‘t cannot load such file -- ./external/CMock/lib/../vendor/unity/auto/type_sanitizer (LoadError)

### ISSUE THREAD

**Issue by Greatpanc** [KhronosGroup/OpenCL-CLHPP#163]
this is my log

cmake .. -DOPENCL_INCLUDE_DIR=/home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/OpenCL-Headers-2020.12.18 -DOPENCL_LIB_DIR=/home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/ -DBUILD_TESTS=ON -DBUILD_DOCS=ON -DBUILD_EXAMPLES=ON
[   28s] -- The C compiler identification is GNU 10.3.1
[   28s] -- The CXX compiler identification is GNU 10.3.1
[   28s] -- Detecting C compiler ABI info
[   28s] -- Detecting C compiler ABI info - done
[   28s] -- Check for working C compiler: /usr/bin/cc - skipped
[   28s] -- Detecting C compile features
[   28s] -- Detecting C compile features - done
[   28s] -- Detecting CXX compiler ABI info
[   28s] -- Detecting CXX compiler ABI info - done
[   28s] -- Check for working CXX compiler: /usr/bin/c++ - skipped
[   28s] -- Detecting CXX compile features
[   28s] -- Detecting CXX compile features - done
[   28s] -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
[   28s] CMake Deprecation Warning at examples/CMakeLists.txt:1 (cmake_minimum_required):
[   28s]   Compatibility with CMake < 2.8.12 will be removed from a future version of
[   28s]   CMake.
[   28s]
[   28s]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
[   28s]   CMake that the project does not need compatibility with older versions.
[   28s]
[   28s]
[   28s] -- Configuring done
[   28s] -- Generating done
[   28s] -- Build files have been written to: /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/build
[   28s] + RPM_EC=0
[   28s] ++ jobs -p
[   28s] + exit 0
[   28s] Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.ipOJ9A
[   28s] + umask 022
[   28s] + cd /home/abuild/rpmbuild/BUILD
[   28s] + '[' /home/abuild/rpmbuild/BUILDROOT/opencl-clhpp-2.0.12-5.oe1.x86_64 '!=' / ']'
[   28s] + rm -rf /home/abuild/rpmbuild/BUILDROOT/opencl-clhpp-2.0.12-5.oe1.x86_64
[   28s] ++ dirname /home/abuild/rpmbuild/BUILDROOT/opencl-clhpp-2.0.12-5.oe1.x86_64
[   28s] + mkdir -p /home/abuild/rpmbuild/BUILDROOT
[   28s] + mkdir /home/abuild/rpmbuild/BUILDROOT/opencl-clhpp-2.0.12-5.oe1.x86_64
[   28s] + cd OpenCL-CLHPP-2.0.12
[   28s] + cd build
[   28s] + make install DESTDIR=/home/abuild/rpmbuild/BUILDROOT/opencl-clhpp-2.0.12-5.oe1.x86_64
[   28s] Scanning dependencies of target headerexampleCL2
[   28s] [  1%] Building CXX object examples/src/CMakeFiles/headerexampleCL2.dir/headerexampleCL2.cpp.o
[   30s] [  3%] Linking CXX executable headerexampleCL2
[   30s] [  3%] Built target headerexampleCL2
[   30s] Scanning dependencies of target trivialCL2SizeTCompat
[   30s] [  5%] Building CXX object examples/src/CMakeFiles/trivialCL2SizeTCompat.dir/trivialCL2SizeTCompat.cpp.o
[   31s] [  7%] Linking CXX executable trivialCL2SizeTCompat
[   31s] [  7%] Built target trivialCL2SizeTCompat
[   31s] Scanning dependencies of target trivialCL2
[   31s] [  9%] Building CXX object examples/src/CMakeFiles/trivialCL2.dir/trivialCL2.cpp.o
[   32s] /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/examples/src/trivialCL2.cpp: In function 'int main()':
[   32s] /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/examples/src/trivialCL2.cpp:239:18: warning: unused variable 'clD' [-Wunused-variable]
[   32s]   239 |     cl_device_id clD = d();
[   32s]       |                  ^~~
[   32s] /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/examples/src/trivialCL2.cpp:240:18: warning: unused variable 'clD2' [-Wunused-variable]
[   32s]   240 |     cl_device_id clD2 = d.get();
[   32s]       |                  ^~~~
[   33s] [ 11%] Linking CXX executable trivialCL2
[   34s] [ 11%] Built target trivialCL2
[   34s] [ 13%] Generating test runner for 2.0
[   34s] [ 15%] Stripping defines from cl.h
[   34s] [ 17%] Generating mocks
[   34s] /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/external/CMock/lib/../vendor/unity/auto/type_sanitizer (LoadError)
[   34s] 	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
[   34s] 	from /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/external/CMock/lib/cmock_generator.rb:43:in `initialize'
[   34s] 	from /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/external/CMock/lib/cmock.rb:25:in `new'
[   34s] 	from /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/external/CMock/lib/cmock.rb:25:in `initialize'
[   34s] 	from /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/external/CMock/lib/cmock.rb:109:in `new'
[   34s] 	from /home/abuild/rpmbuild/BUILD/OpenCL-CLHPP-2.0.12/external/CMock/lib/cmock.rb:109:in `<main>'
[   34s] make[2]: *** [tests/CMakeFiles/test_cl2hpp_300.dir/build.make:87: tests/mocks/Mockcl.c] Error 1
[   34s] make[1]: *** [CMakeFiles/Makefile2:286: tests/CMakeFiles/test_cl2hpp_300.dir/all] Error 2
[   34s] make: *** [Makefile:160: all] Error 2
[   34s] error: Bad exit status from /var/tmp/rpm-tmp.ipOJ9A (%install)

**Comment by Greatpanc** [comment]
This problem is caused by the wrong path of unity, I have solved it, thanks to the community
